version: '3.9'
services:
  database:
    image: mysql:8.0
    env_file:
      - ./docker/env/database.env
    volumes:
      - ./docker/db-data:/var/lib/mysql
    deploy:
      replicas: 1

  mc-banking:
    build:
      context: .
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database
    env_file:
      - ./docker/env/mc-banking.env
      - ./docker/env/database.env
    deploy:
      replicas: 1